# Configuration related to a specific dataset.
# For syntax see: https://github.com/toml-lang/toml#table-of-contents

# Dataset specific common attributes.
[common]

  # The slippy map dataset's base directory.
  dataset = 'D:\BaiduNetdiskDownload\water_dataset'

  # Human representation for classes.
  classes = ['background', 'water']

  # Color map for visualization and representing classes in masks.
  # Note: available colors can be found in `robosat/colors.py`
  colors  = ['denim', 'blue']
 # [weights]
 # values =  [2.659651, 2.175422]
